apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: minimal-ingress
  namespace: default
  annotations:
    ingress.kubernetes.io/ssl-redirect: "false"
spec:
  ingressClassName: nginx  # using nginx helm one
  rules:
    - host: localhost
      http:
        paths:
          - path: /pong
            pathType: Exact
            backend:
              service:
                name: pong-port
                port:
                  number: 80
---
apiVersion: v1
kind: Service
metadata:
  name: pong-port
  namespace: default
spec:
  ports:
    - port: 80
      protocol: TCP
      targetPort: 80
  selector:
    name: pong
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pong
  labels:
    name: pong
spec:
  selector:
    matchLabels:
      name: pong
  replicas: 5
  template:
    metadata:
      labels:
        name: pong
    spec:
      containers:
        - name: pong-api
          image: piotrostr/pong
          ports:
            - containerPort: 80
              protocol: TCP
          resources: {}
      restartPolicy: Always
status: {}
