apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: minimal-ingress
  annotations:
    ingress.kubernetes.io/ssl-redirect: "false"
spec:
  rules:
    - http:
        paths:
          - path: /hello/
            pathType: Prefix
            backend:
              service:
                name: pong-api
                port:
                  number: 80
---
apiVersion: v1
kind: Service
metadata:
  name: pong-lb
  labels:
    name: pong
spec:
  ports:
    - port: 80
      targetPort: 80
  selector:
    name: pong
  type: LoadBalancer
status:
  loadBalancer: {}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pong-deployment
  labels:
    name: pong-api
spec:
  selector:
    matchLabels:
      name: pong
  replicas: 1
  template:
    metadata:
      labels:
        name: pong
    spec:
      containers:
        - name: pong-api
          image: piotrostr/pong
          ports:
            - containerPort: 80
          resources: {}
      restartPolicy: Always
status: {}
